function booking1() {
    document.getElementById("booktab").style.color = "white";
    document.getElementById("booktab").style.background = "#f58024";
    document.getElementById("booking-container").style.display = "block";
    document.getElementById("covid-container").style.display = "none";
    document.getElementById("hotel-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("car-container").style.display = "none";
    document.getElementById("service-container").style.display = "none";
    document.getElementById("covidtab").style.color = "#f58024";
    document.getElementById("covidtab").style.background = "#333333";
    document.getElementById("hoteltab").style.color = "#f58024";
    document.getElementById("hoteltab").style.background = "#333333";
    document.getElementById("bookingnhoteltab").style.background = "#333333";
    document.getElementById("bookingnhoteltab").style.color = "#f58024";
    document.getElementById("carenttab").style.color = "#f58024";
    document.getElementById("carenttab").style.background = "#333333";
    document.getElementById("herotab").style.color = "#f58024";
    document.getElementById("herotab").style.background = "#333333";
}

function covid1() {
    document.getElementById("covidtab").style.color = "white";
    document.getElementById("covidtab").style.background = "#f58024";
    document.getElementById("covid-container").style.display = "block";
    document.getElementById("booking-container").style.display = "none";
    document.getElementById("hotel-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("car-container").style.display = "none";
    document.getElementById("service-container").style.display = "none";
    document.getElementById("booktab").style.color = "#f58024";
    document.getElementById("booktab").style.background = "#333333";
    document.getElementById("hoteltab").style.color = "#f58024";
    document.getElementById("hoteltab").style.background = "#333333";
    document.getElementById("bookingnhoteltab").style.background = "#333333";
    document.getElementById("bookingnhoteltab").style.color = "#f58024";
    document.getElementById("carenttab").style.color = "#f58024";
    document.getElementById("carenttab").style.background = "#333333";
    document.getElementById("herotab").style.color = "#f58024";
    document.getElementById("herotab").style.background = "#333333";
}

function hotel1() {
    document.getElementById("hoteltab").style.color = "white";
    document.getElementById("hoteltab").style.background = "#f58024";
    document.getElementById("hotel-container").style.display = "block";
    document.getElementById("covid-container").style.display = "none";
    document.getElementById("booking-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("car-container").style.display = "none";
    document.getElementById("service-container").style.display = "none";
    document.getElementById("booktab").style.color = "#f58024";
    document.getElementById("booktab").style.background = "#333333";
    document.getElementById("covidtab").style.color = "#f58024";
    document.getElementById("covidtab").style.background = "#333333";
    document.getElementById("bookingnhoteltab").style.background = "#333333";
    document.getElementById("bookingnhoteltab").style.color = "#f58024";
    document.getElementById("carenttab").style.color = "#f58024";
    document.getElementById("carenttab").style.background = "#333333";
    document.getElementById("herotab").style.color = "#f58024";
    document.getElementById("herotab").style.background = "#333333";
}

function bookingnhotel1() {
    document.getElementById("bookingnhoteltab").style.color = "white";
    document.getElementById("bookingnhoteltab").style.background = "#f58024";
    document.getElementById("ticket-container").style.display = "block";
    document.getElementById("booking-container").style.display = "none";
    document.getElementById("covid-container").style.display = "none";
    document.getElementById("hotel-container").style.display = "none";
    document.getElementById("car-container").style.display = "none";
    document.getElementById("service-container").style.display = "none";
    document.getElementById("booktab").style.color = "#f58024";
    document.getElementById("booktab").style.background = "#333333";
    document.getElementById("covidtab").style.color = "#f58024";
    document.getElementById("covidtab").style.background = "#333333";
    document.getElementById("hoteltab").style.background = "#333333";
    document.getElementById("hoteltab").style.color = "#f58024";
    document.getElementById("carenttab").style.color = "#f58024";
    document.getElementById("carenttab").style.background = "#333333";
    document.getElementById("herotab").style.color = "#f58024";
    document.getElementById("herotab").style.background = "#333333";
}

function carent1() {
    document.getElementById("carenttab").style.color = "white";
    document.getElementById("carenttab").style.background = "#f58024";
    document.getElementById("car-container").style.display = "block";
    document.getElementById("booking-container").style.display = "none";
    document.getElementById("covid-container").style.display = "none";
    document.getElementById("hotel-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("service-container").style.display = "none";
    document.getElementById("booktab").style.color = "#f58024";
    document.getElementById("booktab").style.background = "#333333";
    document.getElementById("covidtab").style.color = "#f58024";
    document.getElementById("covidtab").style.background = "#333333";
    document.getElementById("hoteltab").style.background = "#333333";
    document.getElementById("hoteltab").style.color = "#f58024";
    document.getElementById("bookingnhoteltab").style.color = "#f58024";
    document.getElementById("bookingnhoteltab").style.background = "#333333";
    document.getElementById("herotab").style.color = "#f58024";
    document.getElementById("herotab").style.background = "#333333";
}

function hero1() {
    document.getElementById("herotab").style.color = "white";
    document.getElementById("herotab").style.background = "#f58024";
    document.getElementById("service-container").style.display = "block";
    document.getElementById("booking-container").style.display = "none";
    document.getElementById("covid-container").style.display = "none";
    document.getElementById("hotel-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("ticket-container").style.display = "none";
    document.getElementById("car-container").style.display = "none";
    document.getElementById("booktab").style.color = "#f58024";
    document.getElementById("booktab").style.background = "#333333";
    document.getElementById("covidtab").style.color = "#f58024";
    document.getElementById("covidtab").style.background = "#333333";
    document.getElementById("hoteltab").style.background = "#333333";
    document.getElementById("hoteltab").style.color = "#f58024";
    document.getElementById("bookingnhoteltab").style.color = "#f58024";
    document.getElementById("bookingnhoteltab").style.background = "#333333";
    document.getElementById("carenttab").style.color = "#f58024";
    document.getElementById("carenttab").style.background = "#333333";
}